#!/bin/sh

# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

VENDOR=google
DEVICE=gapps

mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary

adb root
adb wait-for-device

echo "Pulling proprietary files..."
for FILE in `cat ../$DEVICE/proprietary-gms-files.txt | grep -v ^# | grep -v ^$`; do
DIR=`dirname $FILE`
    if [ ! -d ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR ]; then
mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
    fi
adb pull /$FILE ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
done

echo "Pulling proprietary apks..."
for FILE in `cat ../$DEVICE/proprietary-gms-apps.txt | grep -v ^# | grep -v ^$`; do
DIR=`dirname $FILE`
    if [ ! -d ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR ]; then
mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
    fi
adb pull /$FILE ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
done

for FILE in `cat ../$DEVICE/proprietary-gms-priv-apps.txt | grep -v ^# | grep -v ^$`; do
DIR=`dirname $FILE`
    if [ ! -d ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR ]; then
mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
    fi
adb pull /$FILE ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
done


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/__VENDOR__/__DEVICE__

PRODUCT_COPY_FILES += \\
EOF

LINEEND=" \\"
COUNT=`cat proprietary-gms-files.txt | grep -v ^# | grep -v ^$ | wc -l | awk {'print $1'}`
for FILE in `cat proprietary-gms-files.txt | grep -v ^# | grep -v ^$`; do
COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
LINEEND=""
    fi
echo " \$(LOCAL_PATH)/proprietary/$FILE:$FILE$LINEEND" >> ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
done


(cat << EOF) > ../../../vendor/$VENDOR/$DEVICE/proprietary/Android.mk
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := \$(call my-dir)
EOF

echo "
PRODUCT_PACKAGES += \\" >> ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
for FILE in `cat ../$DEVICE/proprietary-gms-apps.txt | grep -v ^# | grep -v ^$`; do
  APK_NAME=$(basename $FILE)
  MODULE_NAME=${APK_NAME//\.apk/}

  echo " $MODULE_NAME \\" >> ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
  cat <<- EOF >> ../../../vendor/$VENDOR/$DEVICE/proprietary/Android.mk
include \$(CLEAR_VARS)
LOCAL_MODULE := $MODULE_NAME
LOCAL_SRC_FILES := $FILE
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

EOF
done

LINEEND=" \\"
COUNT=`cat proprietary-gms-priv-apps.txt | grep -v ^# | grep -v ^$ | wc -l | awk {'print $1'}`
for FILE in `cat ../$DEVICE/proprietary-gms-priv-apps.txt | grep -v ^# | grep -v ^$`; do
COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
LINEEND=""
    fi
  APK_NAME=$(basename $FILE)
  MODULE_NAME=${APK_NAME//\.apk/}

  echo " $MODULE_NAME$LINEEND" >> ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
  cat <<- EOF >> ../../../vendor/$VENDOR/$DEVICE/proprietary/Android.mk
include \$(CLEAR_VARS)
LOCAL_MODULE := $MODULE_NAME
LOCAL_SRC_FILES := $FILE
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_PATH := \$(TARGET_OUT_PRIV_APP)
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

EOF
done

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor.mk
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS += vendor/__VENDOR__/__DEVICE__/overlay

\$(call inherit-product, vendor/__VENDOR__/__DEVICE__/__DEVICE__-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

EOF
